version: 0.2

env:
    secrets-manager:
        DISCORD_SECRET: DiscordBot/Secret/Prod:DISCORD_SECRET_PROD

phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
          - echo Writing secret $DISCORD_SECRET to file
          - echo $DISCORD_SECRET > DISCORD_SECRET
    build:
        commands:
          - echo Build started on `date`
          - mvn install
    post_build:
        commands:
          - echo Build finished on `date`
artifacts:
    files:
      - DISCORD_SECRET
      - target/*
      - scripts/*
      - appspec.yml