version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
          - echo Starting build
    build:
        commands:
          - echo Build started on `date`
          - mvn install
    post_build:
        commands:
          - echo Build finished on `date`
artifacts:
    files:
      - target/*
      - scripts/*
      - appspec.yml