version: 0.2

env:
    secrets-manager:
      DISCORD_SECRET_PROD: DiscordBot/Secret/Prod:DISCORD_SECRET
      DISCORD_SECRET_BETA: DiscordBot/Secret/Beta:DISCORD_SECRET

phases:
    install:
        runtime-versions:
            java: latest
    pre_build:
        commands:
          - echo Writing secret $DISCORD_SECRET_PROD to file
          - echo Writing secret $DISCORD_SECRET_BETA to file
          - echo $DISCORD_SECRET_PROD > DISCORD_SECRET_Prod
          - echo $DISCORD_SECRET_BETA > DISCORD_SECRET_Beta
    build:
        commands:
          - echo Build started on `date`
          - mvn install
    post_build:
        commands:
          - echo Build finished on `date`
artifacts:
    files:
      - DISCORD_SECRET_*
      - target/*
      - scripts/*
      - appspec.yml