version: 0.2

env:
  secrets-manager:
    DISCORD_SECRET: arn:aws:secretsmanager:us-west-1:273255435447:secret:DiscordBot:Secret:Prod-ly69g1

phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
          - echo Starting build
    build:
        commands:
          - echo Build started on `date`
          - mvn install
    post_build:
        commands:
          - echo Build finished on `date`
artifacts:
    files:
      - target/*
      - scripts/*
      - appspec.yml